spring.application.name=juno_backend
spring.datasource.url=${DB_URI:jdbc:postgresql://localhost:5432/juno}
spring.datasource.username=${POSTGRES_DB_USER:jun}
spring.datasource.password=${POSTGRES_DB_PASSWORD:jun@}
spring.datasource.driver-class-name=org.postgresql.Driver
api.security.jwt.secret=${JWT_SECRET_KEY}
api.security.jwt.expiration=${JWT_TOKEN_EXPIRATION}   
api.security.jwt.regfresh-token.expiration=${JWT_REFRESH_TOKEN_EXPIRATION}
api.security.jwt.issuer=${JWT_TOKEN_ISSUER}
