spring.application.name=juno_backend
spring.datasource.url=jdbc:postgresql://localhost:5432/juno
spring.datasource.username=${POSTGRES_DB_USER:jun}
spring.datasource.password=${POSTGRES_DB_PASSWORD:jun@}
spring.datasource.driver-class-name=org.postgresql.Driver
