version: '3.8'

services: 
  postgres:
    image: postgres:latest
    container_name: juno_db
    restart: always
    environment: 
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
      POSTGRES_DB: juno_db
    volumes:
      - /database-seed.sql:/docker-entrypoint-initdb.d/database-seed.sql
    ports: 
      - "5432:5432"
volumes:
  postgres_data:
    driver: local