version: '3.8'

services: 
  postgres:
    image: postgres:latest
    container_name: juno_db
    environment: 
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    volumes:
      - ./docker/postgres/db_v3.0.sql:/docker-entrypoint-initdb.d/db_v3.0.sql
      - postgres_data:/var/lib/postgresql/data
    ports: 
      - "5432:5432"

  juno:
    image: juno-server:latest
    container_name: juno_serv
    environment:
      - DB_URI=jdbc:postgresql://postgres:5432/${POSTGRES_DB_NAME}
      - POSTGRES_DB_USER=${POSTGRES_DB_USER}
      - POSTGRES_DB_PASSWORD=${POSTGRES_DB_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRETKEY}
      - JWT_TOKEN_EXPIRATION=${JWT_TOKEN_EXPIRATION}
      - JWT_REFRESH_TOKEN_EXPIRATION=${JWT_REFRESH_TOKEN_EXPIRATION}
      - JWT_TOKEN_ISSUER=${JWT_TOKEN_ISSUER}
    depends_on:
      - postgres
    ports:
      - "8080:8080"
volumes:
  postgres_data: